# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qx < Formula
  desc "Terminal command prefiller that uses Groq AI to generate shell commands"
  homepage "https://github.com/Samuel787/qx"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Samuel787/qx/releases/download/v0.1.3/qx_0.1.3_darwin_amd64.tar.gz"
      sha256 "5d7404f4599098f56e3a6de38294fad060fa89262ec447dd1cf993103633446a"

      def install
        bin.install "qx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Samuel787/qx/releases/download/v0.1.3/qx_0.1.3_darwin_arm64.tar.gz"
      sha256 "cdbfe6216f7d70c83c86db6faf29cffb2eb1ed075311f62b2508ca51bbeffd5e"

      def install
        bin.install "qx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Samuel787/qx/releases/download/v0.1.3/qx_0.1.3_linux_amd64.tar.gz"
      sha256 "4162c6f5a02a3d08d557f02447cc5ffc4f999cf3ef73cda63328a0bca7f86821"
      def install
        bin.install "qx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Samuel787/qx/releases/download/v0.1.3/qx_0.1.3_linux_arm64.tar.gz"
      sha256 "df6c4fc5575eb04fd479649bd1a39c6de21688aeae560ca5176149ffa0ecc7fe"
      def install
        bin.install "qx"
      end
    end
  end
end
